In [1]:
import numpy as np
import matplotlib.pyplot as plt
import os
import csv
from tqdm import tqdm

In [2]:
if(os.path.split(os.getcwd())[1] == "misc"):
    os.chdir("..")
print("Current Working Directory: {}".format(os.path.split(os.getcwd())[1]))

cuda = True

Current Working Directory: progettoVIPM


In [8]:
class Confusion_Matrix_stats():
    def __init__(self, filename):
        
        # Load the data from file

        self.filename = filename

        if ".npy" in filename:
            print("File is readable by numpy")
            self.cm = np.load(filename).astype("float32")
        if ".csv" in filename:
            print("File is readable by csv")
            self.cm = np.loadtxt(filename, delimiter=",", dtype=np.int64)
        
        # Compute basic metrics

        self.accuracy = self.cm.diagonal()/self.cm.sum(axis=1)
        

        prod_matrix = np.ones(self.cm.shape, dtype=np.int8)
        print(prod_matrix)

        np.fill_diagonal(prod_matrix, 0)

        self.false_negative = np.dot(self.cm, prod_matrix).diagonal()

        self.false_positive = np.dot(np.transpose(self.cm), prod_matrix).diagonal()

        self.true_positive = self.cm.diagonal()

        print("sum:{}".format(self.cm.sum()))

        self.real_positive = np.sum(self.cm, axis=1)

        self.real_negative = np.sum(self.cm, axis=0)

        self.true_negative = -self.real_negative + self.cm.sum() - self.real_positive + self.true_positive

        self.predicted_positive = self.true_positive + self.false_positive

        self.predicted_negative = self.true_negative + self.false_negative

        indexes = np.arange(self.cm.shape[0])

        self.accuracy = np.concatenate(([self.accuracy], [indexes]), axis=0)
        print(indexes)

    def show_basic_metric(self):
        print("Showing basic metrics of: {}".format(self.filename))
        print("----------------------------------------------------")
        print("Accuracy: {}".format(self.accuracy))
        print(self.false_negative)
        print(self.false_positive)
        print(self.true_negative)
        print(self.real_positive)
        print(self.real_negative)
        print(self.predicted_positive)
        print(self.predicted_negative)

In [9]:
filename = "prova.csv"
confusion_matrix = Confusion_Matrix_stats(filename)
confusion_matrix.show_basic_metric()

File is readable by csv
[[1 1 1]
 [1 1 1]
 [1 1 1]]
sum:31
[0 1 2]
Showing basic metrics of: prova.csv
----------------------------------------------------
Accuracy: [0.66666667 0.72727273 0.72727273]
[3 3 3]
[3 3 3]
[19 17 17]
[ 9 11 11]
[ 9 11 11]
[ 9 11 11]
[22 20 20]
